-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- CreateIndex
CREATE INDEX "parts_part_number_trgm_idx" ON "parts" USING GIN ("part_number" gin_trgm_ops);

-- NOTE: Prisma's autogenerated diff also included
-- `DROP INDEX "part_embeddings_embedding_hnsw_idx"` here. That line was
-- deleted by hand — Prisma cannot see the hand-written HNSW index (see the
-- comment at the bottom of the init migration and `check-db.ts`'s guard
-- check), so every future `migrate dev` will propose dropping it again.
-- This is not a bug in this migration; it is the same known trap.
