-- NOTE: Prisma's autogenerated diff also included
-- `DROP INDEX "part_embeddings_embedding_hnsw_idx"` here. That line was
-- deleted by hand — Prisma cannot see the hand-written HNSW index (see the
-- comment at the bottom of the init migration and `check-db.ts`'s guard
-- check), so every future `migrate dev` will propose dropping it again.
-- This is not a bug in this migration; it is the same known trap.

-- AlterTable
ALTER TABLE "ingestion_runs" ADD COLUMN     "folder_label" TEXT;

-- AlterTable
ALTER TABLE "parts" ADD COLUMN     "folder_label" TEXT,
ADD COLUMN     "record_number" TEXT;
